#!/usr/bin/env php
<?php
//check for version
if (PHP_MAJOR_VERSION * 10 + PHP_MINOR_VERSION < 81) {
    die('PHP version have to be 8.1 or higher.' . PHP_EOL);
}

//сomposer
require_once(__DIR__ . '/vendor/autoload.php');
//check for output class exists
if (!class_exists('ConsoleAnimated\ConsoleAnimatedOutput')) {
    die('Can not find output library. Try "composer install".' . PHP_EOL);
}

//load
spl_autoload_register(function ($class) {
    foreach (['./src/traits/*.php', './src/exceptions/*.php', './src/*.php','./*.php'] as $mask) {
        $file = str_replace(['\\','*'], [DIRECTORY_SEPARATOR,$class], $mask);
            if (file_exists($file)) {
                require_once($file);
                return true;
            }
    }
    return false;
});


//
$game = new GameLauncher();

